name: joystick_gremlin32
channels:
  - defaults
dependencies:
  - astroid=2.6.6
  - certifi=2020.6.20
  - colorama=0.4.4
  - freetype=2.10.4
  - graphviz=2.38
  - isort=5.9.3
  - jpeg=9d
  - lazy-object-proxy=1.6.0
  - libpng=1.6.37
  - libtiff=4.2.0
  - lz4-c=1.9.3
  - mccabe=0.6.1
  - olefile=0.46
  - pillow=8.3.1
  - pip=21.2.2
  - pylint=2.9.6
  - python=3.6.13
  - reportlab=3.5.67
  - setuptools=58.0.4
  - sqlite=3.37.2
  - tk=8.6.11
  - toml=0.10.2
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - wincertstore=0.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - altgraph==0.17.2
    - future==0.18.2
    - importlib-metadata==4.8.3
    - pefile==2021.9.3
    - pyinstaller==4.10
    - pyinstaller-hooks-contrib==2021.5
    - pypiwin32==223
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pywin32==303
    - pywin32-ctypes==0.2.0
    - typing-extensions==4.0.1
    - zipp==3.6.0
